services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: unicode
      POSTGRES_PASSWORD: unicodedb_0912
      POSTGRES_DB: unicode_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
